import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import type { Stakeholders } from '@/types/analysis'

interface StakeholdersSectionProps {
  data?: Stakeholders
  foiaEmailTemplate?: string
  organizationName?: string
  rfpTitle?: string
}

const StakeholdersSection = ({ data, foiaEmailTemplate, organizationName, rfpTitle }: StakeholdersSectionProps) => {
  console.log('[StakeholdersSection] Received data:', data)

  if (!data) {
    return <div className="no-data">No stakeholder information available</div>
  }

  const handleEmailFOIA = () => {
    if (!foiaEmailTemplate) {
      alert('FOIA email template is not available for this analysis.')
      return
    }

    // Find FOIA contact - prioritize government/FOIA specific contacts
    let foiaRecipient = ''
    let foiaContactName = ''

    // Look for FOIA officer or general contact
    if (data.primaryContacts && data.primaryContacts.length > 0) {
      const foiaContact = data.primaryContacts.find(contact =>
        contact.title?.toLowerCase().includes('foia') ||
        contact.role?.toLowerCase().includes('foia') ||
        contact.title?.toLowerCase().includes('records') ||
        contact.role?.toLowerCase().includes('records')
      )

      if (foiaContact) {
        foiaRecipient = foiaContact.email
        foiaContactName = foiaContact.name
      } else {
        // Fall back to first primary contact
        const primaryContact = data.primaryContacts[0]
        foiaRecipient = primaryContact.email
        foiaContactName = primaryContact.name
      }
    }

    if (!foiaRecipient) {
      alert('No recipient email found. Please add a contact email in the Stakeholders section or search for the organization\'s FOIA office contact.')
      return
    }

    // Generate FOIA request content
    const orgName = organizationName || rfpTitle || 'Organization'
    const subject = `FOIA Request - ${orgName}`

    // Use the FOIA template generated by the backend
    const cleanedTemplate = foiaEmailTemplate.trim().replace(/\\n/g, '\n')

    // Compose full email body
    const fullBody = `${foiaContactName ? `Dear ${foiaContactName},\n\n` : ''}${cleanedTemplate}`

    // Create mailto URL
    const mailtoUrl = `mailto:${foiaRecipient}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(fullBody)}`

    console.log('FOIA Request - Organization:', orgName)
    console.log('FOIA Request - Recipient:', foiaRecipient)
    console.log('FOIA Request - Body length:', fullBody.length)

    window.location.href = mailtoUrl
  }

  const isDark = typeof document !== 'undefined' && document.documentElement.classList.contains('dark')

  // Consistent card styling matching old design
  const cardStyle: React.CSSProperties = {
    border: `1px solid ${isDark ? '#797e93' : '#ddd'}`,
    borderRadius: '8px',
    padding: '16px',
    marginBottom: '12px',
    background: isDark ? '#292f4c' : 'white',
    boxShadow: isDark ? '0 1px 2px rgba(9,11,25,0.5)' : '0 2px 4px rgba(0,0,0,0.1)'
  }

  const cardHeaderStyle = {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '12px'
  }

  const cardTitleStyle: React.CSSProperties = {
    margin: 0,
    fontWeight: 600,
    color: isDark ? '#d5d8df' : '#333'
  }

  return (
    <div className="analysis-content">
      <div className="requirements-list">
        {/* FOIA Email Button */}
        {foiaEmailTemplate && (data.primaryContacts && data.primaryContacts.length > 0) && (
          <div style={{ marginBottom: '16px', display: 'flex', justifyContent: 'flex-end' }}>
            <button
              onClick={handleEmailFOIA}
              className="inline-flex items-center gap-2 rounded-md bg-primary px-3 py-1 text-sm font-medium text-white shadow-sm transition-colors hover:bg-[#0060b9] focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1"
              title="Send FOIA request via email"
              type="button"
            >
              Email FOIA
            </button>
          </div>
        )}

        {/* Primary Contacts */}
        {data.primaryContacts && data.primaryContacts.length > 0 && (
          <>
            <h4 style={{ marginBottom: '12px', fontSize: '16px', fontWeight: 600, color: isDark ? '#d5d8df' : '#333' }}>Primary Contacts</h4>
            {data.primaryContacts.map((contact, i) => (
              <div key={i} className="requirement-card" style={cardStyle}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '8px' }}>
                  <div style={{ flex: 1 }}>
                    <h5 style={{ margin: 0, fontWeight: 600, color: isDark ? '#d5d8df' : '#333', fontSize: '15px' }}>{contact.name}</h5>
                    <p style={{ margin: '4px 0 0 0', fontSize: '14px', color: isDark ? '#c3c6d4' : '#666' }}>{contact.title}</p>
                    {contact.department && <p style={{ margin: '2px 0 0 0', fontSize: '13px', color: isDark ? '#9699a6' : '#999' }}>{contact.department}</p>}
                  </div>
                  <span style={{ padding: '4px 8px', borderRadius: '12px', fontSize: '11px', fontWeight: 600, background: '#dbeafe', color: '#1e40af', border: '1px solid #93c5fd' }}>
                    {contact.influence}
                  </span>
                </div>
                <div style={{ fontSize: '14px', color: isDark ? '#d5d8df' : '#555', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                  {contact.email && (
                    <div>
                      <strong>Email:</strong>{' '}
                      <a href={`mailto:${contact.email}`} style={{ color: isDark ? '#69a7ef' : '#2563eb', fontWeight: 500, textDecoration: 'none' }}>
                        {contact.email}
                      </a>
                    </div>
                  )}
                  {contact.phone && <div><strong>Phone:</strong> {contact.phone}</div>}
                  {contact.role && <div><strong>Role:</strong> {contact.role}</div>}
                </div>
              </div>
            ))}
          </>
        )}

        {/* Decision Makers */}
        {data.decisionMakers && data.decisionMakers.length > 0 && (
          <>
            <h4 style={{ marginBottom: '12px', fontSize: '16px', fontWeight: 600, color: isDark ? '#d5d8df' : '#333', marginTop: '20px' }}>Decision Makers</h4>
            {data.decisionMakers.map((contact, i) => (
              <div key={i} className="requirement-card" style={{ ...cardStyle, background: isDark ? '#30324e' : '#fffaf0' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '8px' }}>
                  <div style={{ flex: 1 }}>
                    <h5 style={{ margin: 0, fontWeight: 600, color: isDark ? '#d5d8df' : '#333', fontSize: '15px' }}>{contact.name}</h5>
                    <p style={{ margin: '4px 0 0 0', fontSize: '14px', color: isDark ? '#c3c6d4' : '#666' }}>{contact.title}</p>
                    {contact.department && <p style={{ margin: '2px 0 0 0', fontSize: '13px', color: isDark ? '#9699a6' : '#999' }}>{contact.department}</p>}
                  </div>
                  <span style={{ padding: '4px 8px', borderRadius: '12px', fontSize: '11px', fontWeight: 600, background: '#fed7aa', color: '#92400e', border: '1px solid #fdba74' }}>
                    {contact.influence}
                  </span>
                </div>
                <div style={{ fontSize: '14px', color: isDark ? '#d5d8df' : '#555', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                  {contact.email && (
                    <div>
                      <strong>Email:</strong>{' '}
                      <a href={`mailto:${contact.email}`} style={{ color: '#2563eb', fontWeight: 500, textDecoration: 'none' }}>
                        {contact.email}
                      </a>
                    </div>
                  )}
                  {contact.phone && <div><strong>Phone:</strong> {contact.phone}</div>}
                  {contact.role && <div><strong>Role:</strong> {contact.role}</div>}
                </div>
              </div>
            ))}
          </>
        )}

        {/* Relationship History */}
        {data.relationshipHistory && (
          <div className="requirement-card" style={cardStyle}>
            <div className="card-header" style={cardHeaderStyle}>
              <h5 style={cardTitleStyle}>Relationship History</h5>
            </div>
            <div className="card-body markdown-content" style={{ padding: 0, margin: 0, fontSize: '14px', color: isDark ? '#d5d8df' : '#555' }}>
              <ReactMarkdown remarkPlugins={[remarkGfm]}>{data.relationshipHistory}</ReactMarkdown>
            </div>
          </div>
        )}

        {/* Communication Preferences */}
        {data.communicationPreferences && (
          <div className="requirement-card" style={cardStyle}>
            <div className="card-header" style={cardHeaderStyle}>
              <h5 style={cardTitleStyle}>Communication Preferences</h5>
            </div>
            <div className="card-body markdown-content" style={{ padding: 0, margin: 0, fontSize: '14px', color: isDark ? '#d5d8df' : '#555' }}>
              <ReactMarkdown remarkPlugins={[remarkGfm]}>{data.communicationPreferences}</ReactMarkdown>
            </div>
          </div>
        )}

        {/* Political Landscape */}
        {data.politicalLandscape && (
          <div className="requirement-card" style={cardStyle}>
            <div className="card-header" style={cardHeaderStyle}>
              <h5 style={cardTitleStyle}>Political Landscape</h5>
            </div>
            <div className="card-body" style={{ padding: '12px', borderRadius: '6px', fontSize: '14px', lineHeight: '1.5', background: '#faf5ff', border: '1px solid #d8b4fe', color: '#6b21a8' }}>
              <ReactMarkdown remarkPlugins={[remarkGfm]}>{data.politicalLandscape}</ReactMarkdown>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default StakeholdersSection
